version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: pre.sh
      timeout: 301
      runas: root
  AfterInstall:
    - location: post.sh
      timeout: 301
      runas: root
